# Permalinks
permalink:           /posts/:title/

# Setup
title:               Talking Rock Labs
tagline:             ''
description:         ''
url:                 https://talkingrock.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Talking Rock Labs
  url:               https://github.com/TalkingRockLabs

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate, jekyll-feed]
